microsoft/mssql-python

- README.md
connection fixed:
`connection_string = ("SERVER=<your_server_name>;DATABASE=<your_database_name>;UID=<your_user_name>;PWD=<your_password>;Encrypt=yes;") connection = mssql_python.connect(connection_string)`
> Update README.md with corrected example

- mssql_python/type.py
This pull request includes a minor change to the `mssql_python/type.py` file. The change ensures compatibility by replacing `datetime.UTC` with `datetime.timezone.utc` in the `TimestampFromTicks` function.
* [`mssql_python/type.py`](diffhunk://#diff-57fcb124a0b5958b9034fbd0c3ee1bc65e4140e1671e642d5dcb5aabd60d55a7L100-R100): Updated the `TimestampFromTicks` function to use `datetime.timezone.utc` instead of `datetime.UTC`, aligning with Python's standard library conventions.
> FIX: Datetime UTC

- eng/pipelines/official-release-pipeline.yml
This pull request updates the `FolderLocation` value in the `official-release-pipeline.yml` file to improve the accuracy of the build process by using the correct directory variable.
Pipeline configuration update:
* [`eng/pipelines/official-release-pipeline.yml`](diffhunk://#diff-f296aaefe400fe34ca36f70a6678007397eeda60a5d3edde7594389f2391cc6fL41-R41): Changed the `FolderLocation` from `$(System.DefaultWorkingDirectory)/dist` to `$(Build.SourcesDirectory)/dist` to ensure the correct directory is used during the release pipeline.
> FIX: Correct ESRP Location for dist

- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
ADO Task ID [AB#37534](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/37534)
This pull request introduces a new header file, `ddbc_bindings.h`, for managing SQL database interactions in the `mssql_python` module. The file provides function pointer typedefs for SQL APIs, extern declarations for these function pointers, and utility classes and functions for logging, exception handling, driver loading, and SQL handle management.
Refactored the native layer to clearly separate binding logic and ODBC utility functions. This decouples the tightly integrated components from ddbc_bindings.cpp. This has been done to improve modularity, reusability, and maintainability of the native …
> REFACTOR: modularize ddbc_bindings.cpp

- mssql_python/pybind/connection/connection.cpp
- mssql_python/pybind/connection/connection.h
- mssql_python/pybind/ddbc_bindings.cpp
ADO Task ID [[AB#34962](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34962)]
This pull request introduces a new `Connection` class for managing MSSQL database connections in the `mssql_python` module. The class provides methods for connecting, disconnecting, handling transactions, and managing autocommit settings. Below are the key changes:
* **Header file (`connection.h`)**:
- Added the `Connection` class definition, including methods for connecting (`connect`), disconnecting (`close`), transaction management (`commit`, `rollback`, `end_transaction`), and autocommit settings (`set_autocommit`, `get_autocommit`).
- Introduced member variables such as `_conn_str` for the connection string, `_env_handle` and `_dbc_handle` for SQL handles, …
> FEAT: adding connection class structure in C++

- mssql_python/pybind/CMakeLists.txt
- mssql_python/pybind/connection/connection.cpp
- mssql_python/pybind/connection/connection.h
This pull request updates the `CMakeLists.txt` file in the `mssql_python/pybind` directory to include a new source file and necessary include directories for building the `ddbc_bindings` module.
Build system updates:
* [`mssql_python/pybind/CMakeLists.txt`](diffhunk://#diff-dbb5892fbbb28149d1639664797cf3adb48ced28ec11aba95f2e2b338ca46badL93-R99): Added `connection/connection.cpp` to the `ddbc_bindings` module sources and included the root and `connection` directories in the `target_include_directories` to ensure proper header file resolution.
> FEAT: update CMakeLists.txt to add new source file and include directories

- mssql_python/connection.py
- mssql_python/cursor.py
- mssql_python/pybind/connection/connection.cpp
- mssql_python/pybind/connection/connection.h
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- tests/test_005_exceptions.py
This pull request makes the database connection and cursor handling in the `mssql_python` module via new C++ `Connection` class and simplifying the Python-side implementation. The changes include replacing low-level connection management with a higher-level abstraction, removing redundant methods, and delegating key operations to the new C++ backend. Below are the most important changes grouped by theme:
* Replaced manual handle allocation (`henv`, `hdbc`) and initialization in `mssql_python/connection.py` with a new `Connection` class from the C++ backend. The `_initializer`, `_allocate_environment_handle`, `_allocate_connection_handle`, and related methods were removed. 
* Simplified transaction methods (`commit`, `rollback`) and connection lifecycle methods (`close`) by delegating …
> FEAT: Integrate python <->C++ flow with C++ connection class

- mssql_python/connection.py
- mssql_python/cursor.py
- mssql_python/pybind/connection/connection.cpp
- mssql_python/pybind/connection/connection.h
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- tests/test_005_exceptions.py
ADO Task ID [[AB#37539](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/37539)]
This pull request introduces a new `Connection` class and supporting infrastructure for managing ODBC database connections in the `mssql_python` project. Key changes include the implementation of the `Connection` class, the addition of function pointer typedefs for ODBC APIs, and the creation of utility classes for driver management and handle lifecycle management.
* [`mssql_python/pybind/connection/connection.cpp`](diffhunk://#diff-eca696c13d997f510e5f9b16288ed1deb0ad132768c283eda1518f78edf9b6ecR1-R110): Implements the `Connection` class, which provides methods for connecting to a database, managing transactions, and configuring autocommit. It uses RAII for …
> FEAT: Implementation of C++ Connection Class API

- eng/pipelines/build-whl-pipeline.yml
- eng/pipelines/pr-validation-pipeline.yml
ADO Task ID: [AB#37623](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/37623)
This pull request updates pipeline configurations to streamline triggers and improve naming conventions. The changes focus on ensuring pipelines are triggered only on relevant events and enhancing clarity in pipeline naming.
Updates to pipeline triggers:
* [`eng/pipelines/build-whl-pipeline.yml`](diffhunk://#diff-a871d64acfb78366b4b077045db53551c2df7d622854569f5f6780ad2ec6f911L4-L9): Modified the trigger to activate only on merges to the `main` branch, removing the `dev` branch from the trigger list.
Enhancements to pipeline naming:
* Renamed `eng/pipelines/test-pipeline.yml` to `eng/pipelines/pr-validation-pipeline.yml` and updated its name within the file for …
> CHORE: Renamed test pipeline and enabled main branch triggers

- eng/pipelines/build-whl-pipeline.yml
- eng/pipelines/pr-validation-pipeline.yml
This pull request updates the Python version used in the build and validation pipelines to address a known issue with Python 3.13.4 and ensure compatibility with Python 3.13.5. The changes include adjustments to the version specifications and relevant comments for clarity.
Pipeline updates:
* [`eng/pipelines/build-whl-pipeline.yml`](diffhunk://#diff-a871d64acfb78366b4b077045db53551c2df7d622854569f5f6780ad2ec6f911L53-R58): Updated the `pythonVersion` for `py313_x64` and `py313_arm64` jobs from `3.13` to `3.13.5` to ensure the use of the latest compatible version.
* [`eng/pipelines/pr-validation-pipeline.yml`](diffhunk://#diff-296c8f902bbd70f34ee1c8c32383c8c99165fe4c8e5b0f234f8f22246e56a621L17-R21): Updated the `versionSpec` in the `UsePythonVersion` task to `3.13.5` and added a comment …
> FIX: Python library linking - not using 3.13.4

- mssql_python/pybind/connection/connection.cpp
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
[AB#37476](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/37476)
This pull request focuses on improving type safety, enhancing error handling, and adding utility functions in the `mssql_python/pybind` module. The changes primarily involve the use of explicit type casting, the introduction of a `WideToUTF8` utility function for string conversion, and minor fixes to improve code clarity and correctness.
* Updated `std::make_shared<SqlHandle>` calls across multiple functions in `connection.cpp` to use `static_cast<SQLSMALLINT>` for handle types (`SQL_HANDLE_ENV`, `SQL_HANDLE_DBC`, `SQL_HANDLE_STMT`) to ensure explicit type casting. [[1]](diffhunk://#diff-eca696c13d997f510e5f9b16288ed1deb0ad132768c283eda1518f78edf9b6ecL30-R30) …
> FIX: Fixing Level 3 and level 4 compiler warnings.

- mssql_python/pybind/CMakeLists.txt
This pull request introduces a platform-specific enhancement to the build configuration for `ddbc_bindings` in the `CMakeLists.txt` file. It adds stricter warning level flags for MSVC to improve code quality.
Build configuration improvement:
* [`mssql_python/pybind/CMakeLists.txt`](diffhunk://#diff-dbb5892fbbb28149d1639664797cf3adb48ced28ec11aba95f2e2b338ca46badR289-R294): Added a conditional block to apply `/W4` (warning level 4) and `/WX` (treat warnings as errors) compiler flags when building with MSVC. This ensures stricter code quality checks for Windows builds.
> FEAT: Enforce Level 3 and 4 warnings as errors to adhere to compliance standards.

- tests/test_003_connection.py
- tests/test_004_cursor.py
This pull request updates the test cases to use temporary tables (prefixed with `#`) instead of permanent tables for improved isolation and to prevent unintended side effects during test execution. The changes span across multiple test functions in the `tests/test_003_connection.py` and `tests/test_004_cursor.py` files.
* Updated all test cases in `tests/test_003_connection.py` to use temporary tables (e.g., `#pytest_test_autocommit`, `#pytest_test_commit`, `#pytest_test_rollback`) instead of permanent tables. This includes changes in table creation, data insertion, selection, and cleanup steps. [[1]](diffhunk://#diff-ca315ffd463e0f93f3d45ace0869a4a3b1e572941da6723d7e9ce028cf9d2278L80-R114) [[2]](diffhunk://#diff-ca315ffd463e0f93f3d45ace0869a4a3b1e572941da6723d7e9ce028cf9d2278L126-R168)
* …
> REFACTOR: Change pytests to use temp tables (starting with #)

- eng/pipelines/pr-validation-pipeline.yml
This pull request adds a new job to the `pr-validation-pipeline.yml` file to enable running Python tests on macOS. The job includes steps for setting up the environment, installing dependencies, building bindings, running tests with coverage, and publishing results. Some Docker-related steps are commented out for now.
* **New job for macOS testing**: Added a `PytestOnMacOS` job to the pipeline, which uses the `macos-latest` image to run Python tests.
* **Python environment setup**: Configured the job to use Python 3.13.5 and installed dependencies from `requirements.txt`.
* **Build and test execution**:
- Built pybind bindings via `build.sh`.
- Ran `pytest` with coverage and published the results.
* Steps for installing and configuring Docker on macOS, including setting up Colima and …
> FEAT: MacOS in PR Validation Pipeline

- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- mssql_python/pybind/ddbc_bindings_mac.cpp
- mssql_python/pybind/mac_utils.cpp
- mssql_python/pybind/mac_utils.h
This pull request refines cross-platform compatibility for the `mssql_python` bindings, improves logging, and simplifies driver loading and function handling. Key changes include replacing Windows-specific code with platform-agnostic alternatives, adding detailed logging for debugging, and introducing macOS-specific handling for wide character conversions.
* Replaced Windows-specific headers (`<shlwapi.h>`) with `<filesystem>` for path handling and removed direct `LoadLibraryW` calls in favor of platform-agnostic dynamic library loading (`LoadDriverLibrary`). [[1]](diffhunk://#diff-dde2297345718ec449a14e7dff91b7bb2342b008ecc071f562233646d71144a1L14-R14) [[2]](diffhunk://#diff-dde2297345718ec449a14e7dff91b7bb2342b008ecc071f562233646d71144a1R544-R579) …
> FEAT: Unify DDBC Bindings - Common Code Consolidation Across Windows/macOS

- tests/test_003_connection.py
This pull request introduces new functionality to test connection pooling in the `mssql_python` library, along with some minor updates to imports in the test file. The most significant changes include adding tests for connection pooling speed and basic functionality, as well as updating the import statement to include the `pooling` module.
* [`tests/test_003_connection.py`](diffhunk://#diff-ca315ffd463e0f93f3d45ace0869a4a3b1e572941da6723d7e9ce028cf9d2278R182-R225): Added `test_connection_pooling_speed` to measure the performance improvement when using connection pooling compared to no pooling. Includes assertions to validate that pooled connections are faster.
* [`tests/test_003_connection.py`](diffhunk://#diff-ca315ffd463e0f93f3d45ace0869a4a3b1e572941da6723d7e9ce028cf9d2278R182-R225): …
> FEAT: adding tests for connection pooling speed and basic functionality

- mssql_python/auth.py
- tests/test_008_auth.py
> [AB#38007](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/38007)
This pull request includes a small change to the `process_auth_parameters` function in `mssql_python/auth.py`. The change adjusts how the `auth_type` is handled for interactive authentication on Windows, ensuring compatibility with native handling of AADInteractive.
> FIX: Interactive on Windows

- mssql_python/type.py
- tests/test_002_types.py
> [AB#38059](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/38059)
This pull request refactors type objects in `mssql_python/type.py` to inherit from their respective Python built-in types, simplifies constructors, and updates related tests to align with the new implementation. Additionally, it modifies timestamp and time handling functions for better compatibility and enhances the `Binary` function to handle multiple input types.
- [`mssql_python/type.py`](diffhunk://#diff-57fcb124a0b5958b9034fbd0c3ee1bc65e4140e1671e642d5dcb5aabd60d55a7L12-R55): Changed type classes (`STRING`, `BINARY`, `NUMBER`, `DATETIME`, `ROWID`) to inherit from Python built-in types (`str`, …
> FIX: Making type objects and constructor compatible with pyodbc

- mssql_python/connection.py
- mssql_python/db_connection.py
- mssql_python/pybind/connection/connection.cpp
- tests/test_003_connection.py
- tests/test_005_connection_cursor_lifecycle.py
> [AB#38059](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/38059)
This pull request updates the default behavior of the `autocommit` setting in the MSSQL Python library, changing it from `True` to `False`. It also includes minor adjustments to tests and imports to reflect this change.
* [`mssql_python/connection.py`](diffhunk://#diff-29bb94de45aae51c23a6426d40133c28e4161e68769e08d046059c7186264e90L150-R150): Updated the `setautocommit` method to default to `False` instead of `True`.
* [`mssql_python/db_connection.py`](diffhunk://#diff-dc442a0da15dacf049752b6c1aa47a48f9e84fb6965215dd3b2457d9cc19de82L8-R8): Modified the `connect` function to set `autocommit` to `False` by …
> FIX: Setting autocommit as False by default & add rollback on connection close

- mssql_python/cursor.py
- tests/test_004_cursor.py
> [AB#34891](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34891)
This pull request introduces the DB-API 2.0-compliant `connection` attribute to the `Cursor` class in `mssql_python`, ensuring that each cursor exposes a read-only reference to its parent connection. The implementation is thoroughly tested with new and updated test cases covering polymorphic code, multi-cursor scenarios, connection lifecycle, and transaction control.
* Added a read-only `connection` property to the `Cursor` class, exposing the connection object used to create the cursor, and updated internal usage to store the connection as a private attribute (`_connection`). (`mssql_python/cursor.py`) …
> FEAT: Adding Cursor.connection attribute

- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- mssql_python/row.py
- tests/test_004_cursor.py
> [AB#34926](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34926)
This pull request adds a new `tables()` method to the `Cursor` class in `mssql_python/cursor.py`, providing a way to query metadata about tables in the database, including support for filtering by name, schema, catalog, and table type. It also introduces comprehensive test coverage for this new method in `tests/test_004_cursor.py`. Additionally, the `skip()` method in the cursor is simplified by delegating to the existing `scroll()` method.
**New feature: Table metadata querying**
- Added a `tables()` method to the `Cursor` class, enabling users to retrieve information about tables with support for filtering …
> FEAT: adding cursor.tables 

- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- mssql_python/row.py
- tests/test_004_cursor.py
> [AB#34893](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34893)
This pull request adds comprehensive support for capturing and managing diagnostic messages (such as SQL Server PRINT statements and warnings) in the `mssql_python` driver's `Cursor` class, following the DBAPI specification. It introduces a new `messages` attribute on the cursor, ensures messages are cleared or preserved at the correct times, and provides robust testing for these behaviors. Additionally, it implements the underlying C++ binding for retrieving all diagnostic records from the ODBC driver.
**Diagnostic message handling improvements:**
* Added a `messages` attribute to the `Cursor` class to store …
> FEAT: Adding Cursor.messages 

- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- mssql_python/row.py
- tests/test_004_cursor.py
> [AB#34924](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34924)
This pull request introduces a new convenience method, `skip`, to the `Cursor` class in `mssql_python/cursor.py`, which allows users to advance the cursor position by a specified number of rows without fetching them. Comprehensive tests have been added to validate the method's behavior, including edge cases and integration with existing fetch methods.
**New feature: Cursor skipping**
* Added `skip(count: int)` method to the `Cursor` class, enabling users to efficiently advance the cursor by a given number of rows without returning those rows. The method checks for closed cursors, validates arguments, supports …
> FEAT: Adding cursor.skip(n)

- mssql_python/constants.py
- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- mssql_python/row.py
- tests/test_004_cursor.py
> [AB#34892](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34892)
This pull request introduces support for emulated scrolling (relative and absolute) in the `Cursor` class for forward-only result sets, including a new `scroll()` method and comprehensive tests for scroll behavior. It also refines row position tracking, improves error handling, and updates some test assertions for clarity. The most important changes are grouped below.
* Added a new `scroll()` method to the `Cursor` class, allowing movement to a specific row position in the result set using relative or absolute modes. This is implemented by consuming rows for forward-only cursors, with robust error handling …
> FEAT: Adding cursor.scoll function

- mssql_python/__init__.py
- mssql_python/connection.py
- mssql_python/helpers.py
- mssql_python/type.py
- tests/test_003_connection.py
> [AB#34917](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34917)
This pull request adds support for configurable text encoding in the `Connection` class of the `mssql_python` package, allowing users to specify how text is encoded when interacting with the database. It introduces new methods for setting and retrieving encoding settings, provides robust validation and error handling, and includes comprehensive tests to ensure correct behavior across a wide range of scenarios.
**Encoding support and configuration:**
* Added `setencoding` and `getencoding` methods to the `Connection` class, allowing users to configure and retrieve text encoding and C type for SQL statements …
> FEAT: Adding conn.setencoding() API

- mssql_python/cursor.py
- mssql_python/pybind/CMakeLists.txt
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
> [AB#33395](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/33395)
This pull request adds support for streaming large parameters to SQL Server using ODBC's Data At Execution (DAE) mechanism, particularly for long Unicode strings and binary data. The changes update both the Python and C++ layers to correctly identify large parameters, mark them for DAE, and handle the streaming process during execution. Additional refactoring improves parameter type mapping and memory handling for these cases.
**Large parameter streaming (DAE) support:**
* Updated the `_map_sql_type` method in `cursor.py` to return an `is_dae` flag for parameters that require …
> FEAT: Support for streaming large parameters in execute()

- eng/pipelines/pr-validation-pipeline.yml
> [AB#38373](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/38373)
This pull request makes a small improvement to the CMake installation step in the PR validation pipeline. The change ensures that any existing installation of CMake is uninstalled before installing a fresh copy, reducing the chance of tap conflicts during setup.
> FIX: MacOS Pipelines CMake Installation

- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- tests/test_004_cursor.py
> [AB#34162](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34162)
[AB#38110](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/38110)
This pull request improves the handling of large object (LOB) columns when fetching data from SQL Server in the `mssql_python/pybind/ddbc_bindings.cpp` file. The main change is to detect LOB columns (such as large strings or binary data) and switch to a per-row fetching strategy using `SQLGetData_wrap` for those columns, ensuring correct streaming and memory usage. For non-LOB columns, the batch fetching logic remains unchanged, but now includes logic to handle LOBs …
> FEAT: LOB detection and fetch strategy for FetchAll and FetchMany

- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- tests/test_004_cursor.py
> [AB#38110](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/38110)
[AB#34162](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34162)
This pull request improves NVARCHAR data handling in the SQL Server Python bindings and adds comprehensive tests for NVARCHAR(MAX) scenarios. The main changes include switching to streaming for large NVARCHAR values, optimizing direct fetch for smaller values, and adding tests for edge cases and boundaries to ensure correctness.
**NVARCHAR data handling improvements:**
* Updated the logic in `ddbc_bindings.cpp` to use streaming for large NVARCHAR/NCHAR columns (over …
> FEAT: streaming support in fetchone for nvarcharmax data type

- main.py
- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- tests/test_004_cursor.py
> [AB#34936](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34936)
[AB#34937](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34937)
This pull request enhances support for SQL Server MONEY and SMALLMONEY types in the Python driver, ensuring correct handling of boundary values, NULLs, and round-trip conversions. It also improves the encoding and decoding of decimal values and adds comprehensive tests to validate the new behavior.
**MONEY and SMALLMONEY Type Handling:**
* Updated `_map_sql_type` in `cursor.py` to detect decimal values within MONEY and SMALLMONEY ranges and bind them as strings, …
> FEAT: Complex Data Type Support- money & smallmoney

- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- tests/test_004_cursor.py
> [AB#34927](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34927)
This pull request adds support for retrieving column metadata from SQL Server using the ODBC `SQLColumns` API, and exposes this functionality to Python through the `columns()` method on the `cursor` class. The implementation includes both backend C++ bindings and a high-level Python interface, as well as careful handling of cursor state and result set mapping.
The most important changes are:
**Python interface:**
* Added a new `columns()` method to the `cursor` class in `mssql_python/cursor.py` to retrieve detailed column metadata for tables using the ODBC `SQLColumns` function. This method includes extensive …
> FEAT: Adding Columns API in cursor

- mssql_python/constants.py
- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- tests/test_004_cursor.py
> [AB#34931](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34931)
This pull request adds support for retrieving primary key information from database tables using a new `primaryKeys` method on the `cursor` object. It introduces the necessary C++/ODBC bindings, Python method, and a comprehensive set of tests to validate the new functionality.
**Primary Key Metadata Support**
* Added a `primaryKeys` method to the `cursor` class in `cursor.py` to allow users to retrieve primary key columns for a specified table, including support for catalog and schema filtering. The method handles ODBC API requirements and result formatting.
**ODBC/C++ Binding Enhancements**
* Introduced the …
> FEAT: Adding primary key API

- mssql_python/constants.py
- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- tests/test_004_cursor.py
> [AB#34932](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34932)
This pull request adds support for retrieving foreign key metadata from SQL Server via ODBC by implementing the `foreignKeys` method in the `Cursor` class and wiring up the necessary C++ bindings for the ODBC `SQLForeignKeys` API. The changes ensure that Python users can now fetch foreign key relationships in a way similar to other database drivers.
**Python interface enhancements:**
* Added a new `foreignKeys` method to the `Cursor` class in `cursor.py`, allowing users to retrieve foreign key metadata for a specified table or referenced table. The method performs input validation, calls the new C++ binding, …
> FEAT: Adding foreignkey API

- mssql_python/constants.py
- mssql_python/cursor.py
- mssql_python/pybind/ddbc_bindings.cpp
- mssql_python/pybind/ddbc_bindings.h
- tests/test_004_cursor.py
> [AB#34934](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/34934)
This pull request adds support for retrieving ODBC data type information via a new `getTypeInfo` method on the `cursor` object, exposing the underlying `SQLGetTypeInfo` API. It includes the necessary C++/Python bindings, error handling, and comprehensive test coverage to ensure correct behavior for different data types and usage scenarios.
* Added a new `getTypeInfo` method to the `cursor` class in `mssql_python/cursor.py`, allowing users to retrieve metadata about supported SQL data types via the ODBC `SQLGetTypeInfo` API. The method supports querying all types or a specific type and returns results as a …
> FEAT: Adding getTypeInfo

- mssql_python/cursor.py
- tests/test_004_cursor.py
> GitHub Issue: https://github.com/microsoft/mssql-python/issues/234
This PR fixes a critical issue where string parameters were being automatically converted to datetime objects, causing failures in SQL queries that require string-to-string comparisons. The fix removes aggressive content-based datetime parsing from the `_map_sql_type()` method while preserving all existing functionality for actual datetime objects.
The mssql-python driver was failing on queries like:
```python
cursor.execute("SELECT * FROM table WHERE RIGHT(column, 10) = ?", ('2025-08-12',))
```
This would throw datetime conversion errors because the driver was automatically trying to parse the string `'2025-08-12'` as a date object, even when it should …
> FIX: Removed aggressive datetime parsing

- PyPI_Description.md
- setup.py
> [AB#38881](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/38881)
This pull request updates the project to version 0.12.0 and revises the release notes to reflect new features and improvements. The most significant changes are the addition of support for new SQL Server data types, enhancements to financial data handling, improvements to development infrastructure, and optimizations to metadata APIs and data processing.
Version and Release Notes Update:
* Updated the project version from `0.11.0` to `0.12.0` in `setup.py`.
* Revised the "What's new" section in `PyPI_Description.md` to:
- Add support for `DATETIMEOFFSET` and `UNIQUEIDENTIFIER` types, with integration for …
> RELEASE: 0.12.0

- PyPI_Description.md
- eng/pipelines/build-whl-pipeline.yml
- mssql_python/pybind/ddbc_bindings.cpp
- setup.py
> [AB#39062](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/39062)
This pull request updates the package to version 0.13.0 and revises the release notes to highlight new features and critical stability improvements. The most important changes are grouped below:
Version update:
* Updated the package version from `0.12.0` to `0.13.0` in `setup.py` to reflect the latest release.
Release notes and feature enhancements (in `PyPI_Description.md`):
* Added support for streaming large values (NVARCHAR/VARCHAR/VARBINARY(MAX)) in `executemany()` with automatic Data-At-Execution detection and fallback, enabling efficient handling of massive datasets.
* Improved batch operations with …
> RELEASE: 0.13.0

- mssql_python/cursor.py
> [AB#39185](https://sqlclientdrivers.visualstudio.com/c6d89619-62de-46a0-8b46-70b92a84d85e/_workitems/edit/39185)
> GitHub Issue: #241 
This pull request removes the logic for automatically mapping UUID string parameters to GUID types in the `_map_sql_type` method of `mssql_python/cursor.py`. As a result, UUID strings will no longer be converted to binary GUID representations when binding parameters.
Type mapping changes:
* Removed the code that attempted to parse parameters as UUIDs and map them to SQL GUID types, so UUID strings will now be handled as regular strings instead of being converted to `bytes_le` for GUID columns.
> FIX: remove checks of string mapping to uuid
